name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
  push:
    paths:
      - projects/project1
    branches:
      - main
  pull_request:
    branches:
      - main
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ github.event }}
      - run: echo ${{ github.ref }}
      - run: tree .
    

