name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.ref_name }}
      - run: tree -a .
    

